services:
  redis-server:
    image: redis:6.2
    container_name: redis-server

  backend:
    build: backend
    environment:
      - REDIS_DNS=redis-server
      - REDIS_PORT=6379
    ports:
      - "9000:9000"
    depends_on:
      - redis-server

  frontend:
    build: frontend
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    ports:
      - "8080:8080"
    depends_on:
      - backend
