version: '3.8'

services:
  redis-server:
    image: redis:6.2
    container_name: redis-server

  backend:
    build: ghcr.io/joachimhviid/fortune-cookie-backend:latest
    environment:
      - REDIS_DNS=redis
    ports:
      - "9000:9000"
    depends_on:
      - redis-server

  frontend:
    build: ghcr.io/joachimhviid/fortune-cookie-frontend:latest
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    ports:
      - "8080:8080"
    depends_on:
      - backend
