apiVersion: v1
kind: Service
metadata:
  labels:
    run: backend
  name: backend-service
spec:
  selector:
    run: backend
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP