apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: fortune-cookie-frontend
        image: ghcr.io/joachimhviid/fortune-cookie-frontend:latest
        env:
          - name: BACKEND_DNS
            value: backend-service
          - name: BACKEND_PORT
            value: "9000"