apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  selector:
    run: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
