name: Build and test
on:
  push:
    branches-ignore:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'

      - name: Build backend
        run: go build
        working-directory: backend
      - name: Build backend
        run: go test
        working-directory: backend

      - name: Build frontend
        run: go build
        working-directory: frontend
      - name: Build frontend
        run: go test
        working-directory: frontend

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Functional-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run function test
        run: bash .github/scripts/function-test.sh
  Lint:
    runs-on: ubuntu-latest
    needs: ['Build']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - name: golangci-lint frontend
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: frontend
          version: v1.59
      - name: golangci-lint backend
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: backend
          version: v1.59
