name: Build and test
on: 
  push:
    branches-ignore:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build application
        run: bash .github/scripts/build-app.sh
      - name: Test application
        run: bash .github/scripts/test-app.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Lint:
    runs-on: ubuntu-latest
    needs: ['Build']
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: code 
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
