name: Deploy application
on: 
  workflow_dispatch:
  push:
    branches:
      - main

env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
          
      - name: Build backend
        run: go build
        working-directory: backend
      - name: Test backend
        run: go test
        working-directory: backend

      - name: Build frontend
        run: go build
        working-directory: frontend
      - name: Test frontend
        run: go test
        working-directory: frontend

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: code 
          path: .
      - name: build docker
        run: bash .github/scripts/build-docker.sh
      - name: push docker
        run: bash .github/scripts/push-docker.sh

  Deploy:
    runs-on: ubuntu-latest
    needs: ['Build', 'Docker-image']
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: code 
          path: .
      - run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - run: kubectl --kubeconfig kubeconfig apply -f ./manifests
