name: Main workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build application
        run: bash .github/scripts/build-app.sh
      - name: Test application
        run: bash .github/scripts/test-app.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: code 
          path: .
      - name: build docker
        run: bash .github/scripts/build-docker.sh
      - name: push docker
        run: bash .github/scripts/push-docker.sh
