name: Main workflow
on: 
  push:
  pull_request: 
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build application
        run: ci/build-app.sh
      - name: Test application
        run: ci/test-app.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
