name: Main workflow
on: 
  push:
  # pull_request: 
  #   branches:
  #     - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build application
        run: .github/scripts/build-app.sh
        shell: bash
      - name: Test application
        run: .github/scripts/test-app.sh
        shell: bash
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code
      #     path: .
