name: Main workflow
on: 
  push:
  pull_request: 
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build application
        run: |
          cd frontend/
          go build
          cd ../backend/
          go build
          cd ..
      - name: Test application
        run: |
          cd frontend/
          go test
          cd ../backend/
          go test
          cd ..
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
